version: 0.1
width: 240
method: sift
sift:
  upsampling: 2
  n_octaves: 8
  n_scales: 3
  sigma_min: 1.6
  sigma_in: 0.5
  c_dog: 0.013333333333333334
  c_edge: 10
  n_bins: 36
  lambda_ori: 1.5
  c_max: 0.8
  lambda_descr: 6
  n_hist: 4
  n_ori: 8
ransac:
  min_samples: 8
  residual_threshold: 1
  max_trials: 100
  stop_sample_num: .inf
  stop_residuals_sum: 0
  stop_probability: 1
  rng: null
orb:
  downscale: 1.2
  n_scales: 8
  n_keypoints: 500
  fast_n: 9
  fast_threshold: 0.08
  harris_k: 0.04
